### ISSUE TITLE
on windows server 2012

### ISSUE THREAD

**Issue by henrikhjelm** [sibblegp/Storj-Dashboard-Client#12]
File "storjreports\storj_service.py", line 69, in <module>
pywintypes.error: (1063, 'StartServiceCtrlDispatcher', 'The service process could not connect to the service controller.')
[4692] Failed to execute script storj_service

**Comment by henrikhjelm** [comment]
C:\Program Files\StorJDash Client>storj_service.exe debug
Debugging service StorJDashSVC - press Ctrl+C to stop.
xxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxx
C:\Users\Administrator\.config\storjshare\configs
Traceback (most recent call last):
  File "storjreports\storj_service.py", line 71, in <module>
  File "site-packages\win32\lib\win32serviceutil.py", line 636, in HandleCommand
Line
  File "site-packages\win32\lib\win32serviceutil.py", line 467, in DebugService
  File "site-packages\win32\lib\win32serviceutil.py", line 835, in SvcRun
  File "storjreports\storj_service.py", line 46, in SvcDoRun
  File "storjreports\send_storj_reports.py", line 182, in windows_main
  File "storjreports\send_storj_reports.py", line 35, in examine_configs
  File "storjreports\send_storj_reports.py", line 119, in send_report
TypeError: argument of type 'int' is not iterable
[1292] Failed to execute script storj_service

**Comment by sibblegp** [comment]
Could you please send me the line you have for "storageAllocation" in one of your node config files please?

**Comment by henrikhjelm** [comment]
you have it in the community chat

**Comment by sibblegp** [comment]
Fix added and scheduled for next release.
