### ISSUE TITLE
No reporting on cron, only on running the command manually.

### ISSUE THREAD

**Issue by georgemaxim** [sibblegp/Storj-Dashboard-Client#20]
Hi,

I have this installed on Ubuntu 16 and seems to work when I issue the command send_storj_reports. I checked the cron entry and it looks like this: 
`#
48 * * * * root /usr/local/bin/send_storj_reports >>/var/log/storj_reports.log 2>&1
`
On installation I got this message as well:
` sudo pip3 install storjdash --upgrade
The directory '/home/george/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/george/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: storjdash in /usr/local/lib/python3.5/dist-packages
Requirement already up-to-date: requests==2.18.4 in /usr/local/lib/python3.5/dist-packages (from storjdash)
Requirement already up-to-date: python-crontab==2.2.5 in /usr/local/lib/python3.5/dist-packages (from storjdash)
Requirement already up-to-date: idna<2.7,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests==2.18.4->storjdash)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests==2.18.4->storjdash)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests==2.18.4->storjdash)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests==2.18.4->storjdash)
Requirement already up-to-date: python-dateutil in /usr/local/lib/python3.5/dist-packages (from python-crontab==2.2.5->storjdash)
Requirement already up-to-date: six>=1.5 in /usr/local/lib/python3.5/dist-packages (from python-dateutil->python-crontab==2.2.5->storjdash)
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
`
On the website it looks like this the attached jpeg, you can see the spike when I update manually, and then the cron updates wrong.

Can you help me figure this out?
![untitled1](https://user-images.githubusercontent.com/10953448/33942774-a4e953da-e01f-11e7-9fec-bee2c6ce4123.jpg)

**Comment by georgemaxim** [comment]
here are some logs from the last run.

`Traceback (most recent call last):
  File "/usr/local/bin/send_storj_reports", line 9, in <module>
    load_entry_point('storjdash==0.3.9', 'console_scripts', 'send_storj_reports')()
  File "/usr/local/lib/python3.5/dist-packages/storjreports/__init__.py", line 5, in run_reports
    send_storj_reports.main()
  File "/usr/local/lib/python3.5/dist-packages/storjreports/send_storj_reports.py", line 184, in main
    examine_configs(settings['configs_directory'])
  File "/usr/local/lib/python3.5/dist-packages/storjreports/send_storj_reports.py", line 27, in examine_configs
    storj_node_pairs = examine_storjstatus()
  File "/usr/local/lib/python3.5/dist-packages/storjreports/send_storj_reports.py", line 73, in examine_storjstatus
    proc = subprocess.Popen(['storjshare', 'status'], env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
NotADirectoryError: [Errno 20] Not a directory
`

**Comment by ubenmackin** [comment]
I think this is the same error as in #24, and has been fixed in the latest change.

@georgemaxim, what is in your config file for storjshare_path? The config file is at /etc/storjdash.json
