### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by vboasso** [sibblegp/Storj-Dashboard-Client#33]
I've got PermissionError: [Errno 13] Permission denied after send_storj_reports even using sudo on Ubuntu
![termsend](https://user-images.githubusercontent.com/29603146/35781108-6b797c8c-09c4-11e8-873f-ffdf07173049.png)

**Comment by mujeerhashmi** [comment]
It fails for me at cron job with the same errors in the log.

`Traceback (most recent call last):
  File "/usr/local/bin/send_storj_reports", line 9, in <module>
    load_entry_point('storjdash==0.3.12', 'console_scripts', 'send_storj_reports')()
  File "/usr/local/lib/python3.5/dist-packages/storjreports/__init__.py", line 5, in run_reports
    send_storj_reports.main()
  File "/usr/local/lib/python3.5/dist-packages/storjreports/send_storj_reports.py", line 193, in main
    examine_configs(settings['configs_directory'])
  File "/usr/local/lib/python3.5/dist-packages/storjreports/send_storj_reports.py", line 29, in examine_configs
    storj_node_pairs = examine_storjstatus()
  File "/usr/local/lib/python3.5/dist-packages/storjreports/send_storj_reports.py", line 76, in examine_storjstatus
    proc = subprocess.Popen(['storjshare', 'status'], env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied`

My crontab entry is 
`01 * * * * root /usr/local/bin/send_storj_reports >>/var/log/storj_reports.log 2>&1`

**Comment by MingLunHan** [comment]
hello, guys.I mean , do you solve this? i MEET THE SAME problem..
