### ISSUE TITLE
Error when running send_storj_report

### ISSUE THREAD

**Issue by mikebzh44** [sibblegp/Storj-Dashboard-Client#37]
Hello.

Everything as working fine untill saturday but now, my node is not reported as running : 

https://imgur.com/SDF7rzy

But when I click on my server name to get the details, it seems OK : 

https://imgur.com/3Gag3Qp

Here is the error I have when running send_storj_reports command : 

```
/usr/local/bin/send_storj_reports
[Errno 5] Input/output error: '/media/Storj/sharddata.kfs/141.s/004958.log'
['Traceback (most recent call last):\n  File "/usr/local/lib/python3.5/dist-packages/storjreports/send_storj_reports.py", line 138, in send_report\n    current_size = get_size_of_path(storage_path)\n  File "/usr/local/lib/python3.5/dist-packages/storjreports/send_storj_reports.py", line 61, in get_size_of_path\n    size += get_size_of_path(item.path)\n  File "/usr/local/lib/python3.5/dist-packages/storjreports/send_storj_reports.py", line 61, in get_size_of_path\n    size += get_size_of_path(item.path)\n  File "/usr/local/lib/python3.5/dist-packages/storjreports/send_storj_reports.py", line 66, in get_size_of_path\n    size += item.stat().st_size\nOSError: [Errno 5] Input/output error: \'/media/Storj/sharddata.kfs/141.s/004958.log\'\n']
All reports sent

```
I try to make an update : 

```
sudo pip3 install storjdash
Requirement already satisfied: storjdash in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: requests==2.18.4 in /usr/local/lib/python3.5/dist-packages (from storjdash)
Requirement already satisfied: python-crontab==2.2.5 in /usr/local/lib/python3.5/dist-packages (from storjdash)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests==2.18.4->storjdash)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests==2.18.4->storjdash)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests==2.18.4->storjdash)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests==2.18.4->storjdash)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.5/dist-packages (from python-crontab==2.2.5->storjdash)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.5/dist-packages (from python-dateutil->python-crontab==2.2.5->storjdash)
```

What can I do to fixe this issue ?

Thanks.

**Comment by mikebzh44** [comment]
Oops, I thin kit's more a Storjshare issue than a StorjDash issue : 

https://docs.storj.io/discuss/5b1615d05c9a620003d4ae47

But is it normal that your program scan all the LOG files in sharddata.kfs dir ?
